substitutions:
  device_description: ${name} gemaakt door huizebruin.nl versie ${vdate}.
  vdate: "v24.2.1" 
  date: "14.12.2023"

preferences:
  flash_write_interval: 120min 

improv_serial:
  
wifi:
  ap:

web_server:
  port: 80
  
captive_portal:

# ⬇ Enable logging ⬇ # 
logger:
  level: INFO
  esp8266_store_log_strings_in_flash: false

  time:
  - platform: homeassistant
    id: time_homeassistant
    on_time_sync:
      - component.update: S0tool_uptime_timestamp  

sensor:
#------------------------#  sensoren #------------------------#
  - platform: uptime
    id: tempsensor_uptime

  - platform: template
    id: tempsensor_uptime_timestamp
    name: "${name} online sinds"
    device_class: "timestamp"
    accuracy_decimals: 0
    update_interval: never
    icon: 'mdi:clock-start'
    entity_category: diagnostic
    lambda: |-
      static float timestamp = (
        id(time_homeassistant).utcnow().timestamp - id(S0tool_uptime).state
      );
      return timestamp;  

# ⬇ versie verbinding informatie sensoren voor in ha ⬇ #
  # WiFi signal
  - platform: wifi_signal
    name: "${name} - WiFi Signal"
    update_interval: 120s
    
text_sensor:
  - platform: template
    name: "tempsensor_versie"
    id: tempsensor_versie
    icon: 'mdi:alpha-v-circle-outline' 
    update_interval: 6h
    entity_category: diagnostic
    lambda: |-
      return {"${vdate}"};

  - platform: wifi_info
    ip_address:
      name: "${name} IP-adres"
      id: s0tool_ip_adres
      icon: mdi:ip-network

    mac_address:
      name: "${name} Mac-adres"
      id: s0tool_mac_adres
      icon: mdi:folder-key-network-outline
